### PR TITLE
1.3.8

### PR DESCRIPTION
**Pull request by fengjiachun**
* [x] unit test
 * [x] [jepsen verification](https://github.com/sofastack/sofa-jraft-jepsen)
    - [x] configuration-test: remove and add a random node
    - [x] bridge-test: weaving the network into happy little intersecting majority rings
    - [x] pause-test: pausing random node with SIGSTOP/SIGCONT
    - [x] crash-test: killing random nodes and restarting them
    - [x] partition-test: Cuts the network into randomly chosen halves
    - [x] partition-majority-test: Cuts the network into randomly majority groups
 * [x] release note
 * [ ] release

## 1.3.8

2021-08-09

- Features
    - Snapshot 支持并行压缩/解压缩，充分利用多核，加速在 snapshot 较大的时的 load 和 save 速度 #603 
    - CliService 提供 learner 到 follower 的转换 API
    - Node 暴露 getNodeState API 方便运维使用
    
- Bug Fixes
    - 修复 install snapshot retry 失败的 bug #606 
    - 一些 help GC 的优化 #619 #629 
    - 修复 segment log 的 producer 和 consumer 之间可能发生的死锁 #649 
    - 修复在 replicator 销毁时移除相应的 metric 失败 #643 
    - 修复 RheaKV 在成员发生变更时没有刷新路由表的 bug #652 

- Breaking Changes
    - 无

- 致谢（排名不分先后）
@seeflood @a364176773 @horizonzy @hzh0425 @xiaoheng1 @312223105

### CODE REVIEW

**Comment by fengjiachun** [comment]
```
INFO [2021-08-10 11:22:38,853] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :linear
 {:valid? true, :model {:value 1}, :final-paths (), :configs ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by fengjiachun** [comment]
bridge-test: weaving the network into happy little intersecting majority rings

```
INFO [2021-08-10 11:28:31,218] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 2},
    :last-op
    {:process 4,
     :type :ok,
     :f :read,
     :value 2,
     :index 5045,
     :time 145509198584},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by fengjiachun** [comment]
pause-test: pausing random node with SIGSTOP/SIGCONT

```
INFO [2021-08-10 11:39:53,459] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :linear
 {:valid? true, :model {:value 3}, :final-paths (), :configs ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by fengjiachun** [comment]
crash-test: killing random nodes and restarting them

```
INFO [2021-08-10 11:43:44,499] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :linear
 {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by fengjiachun** [comment]
partition-test: Cuts the network into randomly chosen halves

```
INFO [2021-08-10 11:47:47,492] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :indep
 {:valid? true,
  :results
  {0
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 4,
        :type :ok,
        :f :read,
        :value 3,
        :index 200,
        :time 3978957250},
       :pending []}),
     :final-paths ()},
    :valid? true},
   7
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 2,
        :index 1615,
        :time 31999444834},
       :pending []}),
     :final-paths ()},
    :valid? true},
   1
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
    :valid? true},
   4
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 15,
        :type :ok,
        :f :write,
        :value 0,
        :index 1002,
        :time 20211919125},
       :pending []}
      {:model {:value 4},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 4,
        :index 1001,
        :time 20211908292},
       :pending []}),
     :final-paths ()},
    :valid? true},
   15
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 16,
        :type :ok,
        :f :cas,
        :value [1 4],
        :index 3223,
        :time 55474351667},
       :pending []}),
     :final-paths ()},
    :valid? true},
   13
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 1}, :final-paths (), :configs ()},
    :valid? true},
   6
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 1410,
        :time 29062930625},
       :pending
       [{:process 15,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1386,
         :time 26984730709}
        {:process 19,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1398,
         :time 27463114667}]}
      {:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 1410,
        :time 29062930625},
       :pending
       [{:process 15,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1386,
         :time 26984730709}]}
      {:model {:value 1},
       :last-op
       {:process 28,
        :type :ok,
        :f :write,
        :value 1,
        :index 1409,
        :time 29053425000},
       :pending
       [{:process 12,
         :type :invoke,
         :f :write,
         :value 3,
         :index 1393,
         :time 27161346584}]}
      {:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 1410,
        :time 29062930625},
       :pending
       [{:process 12,
         :type :invoke,
         :f :write,
         :value 3,
         :index 1393,
         :time 27161346584}
        {:process 15,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1386,
         :time 26984730709}
        {:process 19,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1398,
         :time 27463114667}]}
      {:model {:value 4},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 4,
        :index 1411,
        :time 29068799625},
       :pending
       [{:process 12,
         :type :invoke,
         :f :write,
         :value 3,
         :index 1393,
         :time 27161346584}
        {:process 15,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1386,
         :time 26984730709}
        {:process 23,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1387,
         :time 27007574625}]}
      {:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 1410,
        :time 29062930625},
       :pending
       [{:process 12,
         :type :invoke,
         :f :write,
         :value 3,
         :index 1393,
         :time 27161346584}
        {:process 23,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1387,
         :time 27007574625}]}
      {:model {:value 1},
       :last-op
       {:process 28,
        :type :ok,
        :f :write,
        :value 1,
        :index 1409,
        :time 29053425000},
       :pending
       [{:process 15,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1386,
         :time 26984730709}
        {:process 19,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1398,
         :time 27463114667}
        {:process 23,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1387,
         :time 27007574625}]}
      {:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 1410,
        :time 29062930625},
       :pending []}
      {:model {:value 4},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 4,
        :index 1411,
        :time 29068799625},
       :pending
       [{:process 19,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1398,
         :time 27463114667}
        {:process 23,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1387,
         :time 27007574625}]}
      {:model {:value 4},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 4,
        :index 1411,
        :time 29068799625},
       :pending
       [{:process 12,
         :type :invoke,
         :f :write,
         :value 3,
         :index 1393,
         :time 27161346584}
        {:process 19,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1398,
         :time 27463114667}]}),
     :final-paths ()},
    :valid? true},
   17
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 30,
        :type :ok,
        :f :cas,
        :value [0 4],
        :index 3559,
        :time 60400447417},
       :pending []}),
     :final-paths ()},
    :valid? true},
   3
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 15,
        :type :ok,
        :f :read,
        :value 1,
        :index 804,
        :time 17401382375},
       :pending []}),
     :final-paths ()},
    :valid? true},
   12
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 6,
        :type :ok,
        :f :write,
        :value 0,
        :index 2621,
        :time 46472738834},
       :pending []}),
     :final-paths ()},
    :valid? true},
   2
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 15,
        :type :ok,
        :f :read,
        :value 4,
        :index 607,
        :time 15091822292},
       :pending
       [{:process 1,
         :type :invoke,
         :f :write,
         :value 4,
         :index 403,
         :time 12485034667}
        {:process 10,
         :type :invoke,
         :f :write,
         :value 0,
         :index 414,
         :time 12628257292}]}
      {:model {:value 4},
       :last-op
       {:process 15,
        :type :ok,
        :f :read,
        :value 4,
        :index 607,
        :time 15091822292},
       :pending
       [{:process 1,
         :type :invoke,
         :f :write,
         :value 4,
         :index 403,
         :time 12485034667}]}
      {:model {:value 4},
       :last-op
       {:process 15,
        :type :ok,
        :f :read,
        :value 4,
        :index 607,
        :time 15091822292},
       :pending
       [{:process 10,
         :type :invoke,
         :f :write,
         :value 0,
         :index 414,
         :time 12628257292}]}
      {:model {:value 4},
       :last-op
       {:process 15,
        :type :ok,
        :f :read,
        :value 4,
        :index 607,
        :time 15091822292},
       :pending []}),
     :final-paths ()},
    :valid? true},
   11
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 20,
        :type :ok,
        :f :read,
        :value 1,
        :index 2415,
        :time 43926331500},
       :pending []}),
     :final-paths ()},
    :valid? true},
   9
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 17,
        :type :ok,
        :f :read,
        :value 2,
        :index 2011,
        :time 37934058459},
       :pending []}),
     :final-paths ()},
    :valid? true},
   5
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 23,
        :type :ok,
        :f :write,
        :value 2,
        :index 1208,
        :time 23810924667},
       :pending []}
      {:model {:value 4},
       :last-op
       {:process 15,
        :type :ok,
        :f :write,
        :value 4,
        :index 1207,
        :time 23810924667},
       :pending []}),
     :final-paths ()},
    :valid? true},
   14
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 16,
        :type :ok,
        :f :write,
        :value 0,
        :index 3020,
        :time 52303064750},
       :pending []}),
     :final-paths ()},
    :valid? true},
   16
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 22,
        :type :ok,
        :f :read,
        :value 4,
        :index 3424,
        :time 58671447542},
       :pending []}),
     :final-paths ()},
    :valid? true},
   10
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 24,
        :type :ok,
        :f :write,
        :value 1,
        :index 2216,
        :time 41250296750},
       :pending []}),
     :final-paths ()},
    :valid? true},
   8
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 28,
        :type :ok,
        :f :read,
        :value 4,
        :index 1819,
        :time 35145023917},
       :pending []}),
     :final-paths ()},
    :valid? true}},
  :failures []},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by seeflood** [comment]
Are these comments automatically submited by robot,or you just do it yourself....

**Comment by fengjiachun** [comment]
partition-majority-test: Cuts the network into randomly majority groups
```
INFO [2021-08-10 11:55:42,107] main - jepsen.core {:perf
 {:latency-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$point_graph_BANG_$fn__2988.invoke (perf.clj:264)\n    jepsen.checker.perf$point_graph_BANG_.invokeStatic (perf.clj:263)\n    jepsen.checker.perf$point_graph_BANG_.invoke (perf.clj:248)\n    jepsen.checker$latency_graph$reify__3665.check (checker.clj:413)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :rate-graph
  {:valid? :unknown,
   :error
   "java.lang.IllegalStateException: Error rendering plot, verify gnuplot is installed and reachable\n at jepsen.checker.perf$rate_graph_BANG_.invokeStatic (perf.clj:375)\n    jepsen.checker.perf$rate_graph_BANG_.invoke (perf.clj:351)\n    jepsen.checker$rate_graph$reify__3668.check (checker.clj:422)\n    jepsen.checker$check_safe.invokeStatic (checker.clj:71)\n    jepsen.checker$check_safe.invoke (checker.clj:64)\n    jepsen.checker$compose$reify__3577$fn__3579.invoke (checker.clj:87)\n    clojure.core$pmap$fn__8105$fn__8106.invoke (core.clj:6942)\n    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)\n    clojure.lang.AFn.call (AFn.java:18)\n    java.util.concurrent.FutureTask.run (FutureTask.java:266)\n    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)\n    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)\n    java.lang.Thread.run (Thread.java:748)\n"},
  :valid? :unknown},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 0},
    :last-op
    {:process 1,
     :type :ok,
     :f :read,
     :value 0,
     :index 4567,
     :time 145020418625},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

```

**Comment by fengjiachun** [comment]
> Are these comments automatically submited by robot,or you just do it yourself....

Don't think too more. I did it manually. :)

**Comment by fengjiachun** [comment]
ヽ(‘ー`)ノ

**Comment by seeflood** [comment]
ヽ(‘ー`)ノ

**Review by SteNicholas — APPROVED** [review]

**Pull request merged**
