### PR TITLE
(fix) Flush output stream before calling fd.sync, #480

### LINKED ISSUE #480: Snapshot metadata lost after node panic back.
### Describe the bug
Utils.atomicMoveFile() can't guaranteed data consistency and sync to disk.

sofa-jraft/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/io/ProtoBufFile.java::save() method has issues which can case snapshot metadata lost.

which let _**syncMeta = true**_ doesn't works as expect;

Risk 1:  no output flush after output write. some data in buffer cache; 

Risk 2:  Like 1, move tmp file to final metadata file looks like a atomic operation but the target file isn't sync to disk.

### Expected behavior
If enduser do concerned about data safety, current code cant guaranteed this.

### Actual behavior
In our regular test, we see this symptoms: (sorry, hide some path infos)

total 16K
drwxr-xr-x. 4 root root  33 Jul  3 08:29 kv
-rw-r--r--. 1 root root 16K Jul  2 20:14 kv.zip
**_-rw-r--r--. 1 root root   0 Jul  2 20:14 __raft_snapshot_meta_**

_raft_snapshot_meta file size 0, which cause node init failed;

2020-07-02 20:26:15.834 [main] INFO  FSMCallerImpl:201 - Starts FSMCaller successfully.
2020-07-02 20:26:15.845 [main] ERROR LocalSnapshotReader:91 - **_Fail to load snapshot meta_** $PATH_TO_SNAPSHOT/snapshot/snapshot_1065/__raft_snapshot_meta.
2020-07-02 20:26:15.846 [main] ERROR LocalSnapshotStorage:313 - **_Fail to init reader for path_** $PATH_TO_SNAPSHOT/snapshot/snapshot_1065.
2020-07-02 20:26:15.846 [main] ERROR NodeImpl:977 - Node $NODE_INFO is **_initialized with inconsistent log_**, status=Status[EIO<1014>: Missing logs in (0, 778)].

### Steps to reproduce
There is a unit test can reproduce this issue, if you do some modifications.

sofa-jraft/jraft-core/src/test/java/com/alipay/sofa/jraft/storage/io/ProtobufFileTest.java::testSaveLoad()

1.  don't use /tmp menu
2. panic server without system sync. after line 42  **_` assertTrue(file.save(msg, true));`_**,  after panic server back, you will see this issue with that file.

but if you `sync` before panic, this won't happen. That is why I say, _**syncMeta = true**_ doesn't works as expect;

### Environment

- SOFAJRaft version:
v1.3.0

- JVM version (e.g. `java -version`):
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

- OS version (e.g. `uname -a`):
Kernel:  5.4.22
OS Version: Centos &

- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by killme2008**
### Motivation:

#480 

### Modification:

Flush output stream before calling `FileDescriptor#sync` in `ProtoBufFile.save` method. I also checked other code that do this stuff,  they looks fine.

### Result:

Fixes #480 .

It's a fatal issue, we should release a new version ASAP.

### CODE REVIEW

**Comment by killme2008** [comment]
@fengjiachun @zongtanghu 这个有空抓紧看下，需要发一个版本

**Comment by fengjiachun** [comment]
> @fengjiachun @zongtanghu 这个有空抓紧看下，需要发一个版本

需要整理下代码缩进

**Comment by killme2008** [comment]
@fengjiachun 用了格式化命令了，会乱

**Comment by zongtanghu** [comment]
Maybe, it will be better that adding some unit test case?

**Comment by killme2008** [comment]
@zongtanghu It's hard to test this case in unit test, because we can't mock system crash in java simply. I think we should verify it in chaos test.

**Comment by zongtanghu** [comment]
> @zongtanghu It's hard to test this case in unit test, because we can't mock system crash in java simply. I think we should verify it in chaos test.

@killme2008 ok, it's nice!

**Comment by killme2008** [comment]
@fengjiachun It can be merged.

**Pull request merged**
