### PR TITLE
release: 1.3.12

### PR DESCRIPTION
**Pull request by fengjiachun**
* [x] unit test
 * [ ] [jepsen verification](https://github.com/sofastack/sofa-jraft-jepsen)
    - [x] configuration-test: remove and add a random node
    - [x] bridge-test: weaving the network into happy little intersecting majority rings
    - [x] pause-test: pausing random node with SIGSTOP/SIGCONT
    - [x] crash-test: killing random nodes and restarting them
    - [x] partition-test: Cuts the network into randomly chosen halves
    - [x] partition-majority-test: Cuts the network into randomly majority groups

 * [x] release note
 * [ ] release

## 1.3.12

~~2022-11-28~~
2022-12-13

- Features
    - Custom thread pool instead of global thread pool #853 #855
    - `ReadOnlyOption` can be set individually for each request #867 
    - RheaKV supports setting compression levels for snapshots #875 
    - New API for getting last log indexes #880 #879 
    - Upgrade RocksDB to v7.7.3 #896
    - Upgrade gRPC to v1.50.2 #904

 - Bug Fixes
    - Fixes `exec-maven-plugin unkown` error #878 
    - Fixes `NodeOptions.copy() without base class RpcOptions` #902 
    - RheaKV bugfix: `containsKey` inconsistent results returned after Snapshot #905 #909
  

- Breaking Changes
    - 无

- 致谢（排名不分先后）
@shihuili1218 @nobodyiam @qiujiayu @xtr1993 @killme2008 @lfygh @KomachiSion

### CODE REVIEW

**Review by nobodyiam — APPROVED** [review]
LGTM

**Comment by fengjiachun** [comment]
# configuration-test: remove and add a random node

     {:process 661,
      :type :invoke,
      :f :cas,
      :value [4 2],
      :index 1946,
      :time 120602484125}
     {:process 663,
      :type :invoke,
      :f :cas,
      :value [2 3],
      :index 1968,
      :time 121853782250}
     {:process 664,
      :type :invoke,
      :f :cas,
      :value [0 0],
      :index 1952,
      :time 120906329500}
     {:process 667,
      :type :invoke,
      :f :cas,
      :value [4 4],
      :index 1963,
      :time 121550483833}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
#  bridge-test: weaving the network into happy little intersecting majority rings

     {:process 628,
      :type :invoke,
      :f :write,
      :value 1,
      :index 1921,
      :time 122062915084}
     {:process 629,
      :type :invoke,
      :f :cas,
      :value [3 2],
      :index 1891,
      :time 120266050542}
     {:process 632,
      :type :invoke,
      :f :cas,
      :value [2 2],
      :index 1903,
      :time 120897473000}
     {:process 635,
      :type :invoke,
      :f :write,
      :value 0,
      :index 1908,
      :time 121314664542}
     {:process 638,
      :type :invoke,
      :f :cas,
      :value [0 0],
      :index 1915,
      :time 121720320834}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
# pause-test: pausing random node with SIGSTOP/SIGCONT

     {:process 386,
      :type :invoke,
      :f :write,
      :value 0,
      :index 1135,
      :time 120230896500}
     {:process 389,
      :type :invoke,
      :f :write,
      :value 0,
      :index 1148,
      :time 120941066834}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
# crash-test: killing random nodes and restarting them
     {:process 647,
      :type :invoke,
      :f :write,
      :value 4,
      :index 1938,
      :time 121243154708}
     {:process 648,
      :type :invoke,
      :f :write,
      :value 3,
      :index 1952,
      :time 122098746458}
     {:process 650,
      :type :invoke,
      :f :write,
      :value 3,
      :index 1945,
      :time 121680306291}
     {:process 653,
      :type :invoke,
      :f :cas,
      :value [2 1],
      :index 1951,
      :time 121951231875}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
# partition-test: Cuts the network into randomly chosen halves

        {:process 431,
         :type :invoke,
         :f :write,
         :value 4,
         :index 1196,
         :time 55100695875}
        {:process 433,
         :type :invoke,
         :f :write,
         :value 1,
         :index 1216,
         :time 56035779958}
        {:process 434,
         :type :invoke,
         :f :write,
         :value 0,
         :index 1201,
         :time 55376397875}
        {:process 437,
         :type :invoke,
         :f :cas,
         :value [0 1],
         :index 1208,
         :time 55684130791}]}),
     :final-paths ()},
    :valid? true}},
  :failures []},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Comment by fengjiachun** [comment]
# partition-majority-test: Cuts the network into randomly majority groups

     {:process 679,
      :type :invoke,
      :f :write,
      :value 0,
      :index 1980,
      :time 121345061666}
     {:process 682,
      :type :invoke,
      :f :write,
      :value 2,
      :index 1986,
      :time 121617752041}
     {:process 685,
      :type :invoke,
      :f :write,
      :value 4,
      :index 1993,
      :time 121925202958}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? :unknown}


Everything looks good! ヽ(‘ー`)ノ

**Pull request merged**
