### PR TITLE
fix MetadataRpcClient#getClusterInfo returns null

### LINKED ISSUE #537: c.a.s.j.c.StateMachineAdapter            : onStartFollowing: LeaderChangeContext [leaderId=192.168.12.1:8181, term=774, status=Status[ENEWLEADER<10011>: Follower receives message from new leader with the same term.]].

### LINKED ISSUE #584: MetadataRpcClient.getClusterInfo always return null
### Describe the bug

As described in the title,  MetadataRpcClient.getClusterInfo always returns a null value in remote PD mode.

### Expected behavior

Return the actual cluster information.

### Actual behavior

Return a null.

### Steps to reproduce

Connect to remote Pd, and call this function

### Possible Cause

See GetClusterInfoResponse.

```java
// entends BaseResponse<Cluster> instead
public class GetClusterInfoResponse extends BaseResponse {

    private static final long serialVersionUID = 8811355826978037463L;

    private Cluster           cluster;

    public Cluster getCluster() {
        return cluster;
    }

    public void setCluster(Cluster cluster) {
        this.cluster = cluster;
    }

    @Override
    public String toString() {
        return "GetClusterInfoResponse{" + "cluster=" + cluster + "} " + super.toString();
    }
}
```

Maybe we should extend BaseResponse<Cluster> so that the decoder can correctly set the data in BaseReponse. And in  DefaultPlacementDriverService.handleGetClusterInfoRequest we should use respose.setData instead of response.setCluster. 

If there is no problem with my understanding, I can create a pull request to fix this bug. And please let me know if I am wrong. 

### Environment
 
- SOFAJRaft version: 1.3.6
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by stream2000**
### Motivation:

When calling MetadataRpcClient#getClusterInfo to get cluster information from remote Pd, it always returns a null.

### Modification:

Modify GetClusterInfoReponse and DefaultPlacementDriverService to rightly return the cluster information

### Result:
 
Fixes #537

### CODE REVIEW

**Comment by fengjiachun** [comment]
@stream2000 you need to sign  CLA

**Comment by stream2000** [comment]
> @stream2000 you need to sign CLA

I have signed the CLA but the bot didn't update..

**Review by horizonzy — APPROVED** [review]
LGTM.

**Comment by fengjiachun** [comment]
LGTM

**Pull request merged**
