### PR TITLE
(feat) Improve readme

### PR DESCRIPTION
**Pull request by killme2008**
### Motivation:

Update readme to describe new features.

### CODE REVIEW

**Comment by fengjiachun** [comment]
Also need to update https://github.com/sofastack/sofa-jraft/blob/master/README_zh_CN.md

**Comment by SteNicholas** [comment]
And update https://www.sofastack.tech/projects/sofa-jraft/overview/

**Comment by fengjiachun** [comment]
> Updated https://www.sofastack.tech/projects/sofa-jraft/overview/.

👍

**Comment by SteNicholas** [comment]
@fengjiachun You could merge this.

**Pull request merged**
