### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by seeflood**
Add community and end users.

### CODE REVIEW

**Comment by SteNicholas** [comment]
@seeflood , please fork the repo and then create the pull request.

**Comment by seeflood** [comment]
> @seeflood , please fork the repo and then create the pull request.

ok

**Comment by seeflood** [comment]
> @seeflood , please fork the repo and then create the pull request.

Sorry to bother you,but my network went unavailable now:(
I will do it tomorrow.

**Comment by seeflood** [comment]
@SteNicholas Hi,I followed your advice and opened another PR,so this PR could be closed

**Pull request closed without merging**
