### PR TITLE
chore: remove deprecated method to adapt higher rocksdb version

### LINKED ISSUE #1057: support higher rocksdb version
### Your question

Describe your question clearly

image

in higher version of rocksdb， org.rocksdb,BlockBasedTableConfig.blockCacheCompressedSize()j has been removed
https://github.com/facebook/rocksdb/blob/8d50a7c9df2352e4949aa456206bbd7b9ee49620/java/src/main/java/org/rocksdb/BlockBasedTableConfig.java#L13
### Your scenes

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

remove this settings

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by leizhiyuan**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

after upgrade the new version， I removed all deprecated method  

### Result:

Fixes #1057

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by leizhiyuan** [comment]
after test case succeeded, I will restore the default rocksdb config

**Comment by RongtongJin** [comment]
Looking forward to merging soon, RocketMQ is introducing jraft, but jraft has employed deprecated methods from an older version of rocksdb, resulting in unexpected startup failures.

**Comment by leizhiyuan** [comment]
cc @fengjiachun

**Comment by RongtongJin** [comment]
Hi @fengjiachun , I'm curious to know whether there's an upcoming release planned in the near future. We are looking forward that JRaft can be applied to RocketMQ ASAP :-) https://github.com/apache/rocketmq/pull/7301

**Comment by fengjiachun** [comment]
I plan to release  this month(maybe as soon as next week). I will first do a Jepsen validation, and once it has been verified, I will proceed to the release. The detailed process will be continuously updated in this [issue](https://github.com/sofastack/sofa-jraft/issues/1064).

**Comment by fengjiachun** [comment]
@RongtongJin @leizhiyuan  https://github.com/sofastack/sofa-jraft/issues/1064

**Comment by leizhiyuan** [comment]
thanks，we will test soon

**Pull request merged**
