### PR TITLE
Solve the potential security risk issue of jackson-databind.

### LINKED ISSUE #469: The potential security risk of jackson-databind.
Your question
There exists some network security risk of jackson-databind.

Your scenes
There exists some network security risk of jackson-databind.

Your advice
I will upgrade the version of jackson-databind to solve the potential security risks.

Environment
SOFAJRaft version:
JVM version (e.g. java -version):
OS version (e.g. uname -a):
Maven version:
IDE version:

### PR DESCRIPTION
**Pull request by zongtanghu**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #469.

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by SteNicholas** [comment]
LGTM

**Comment by SteNicholas** [comment]
@zongtanghu Please check the CI failure.

**Comment by zongtanghu** [comment]
image

Because of the class com.fasterxml.jackson.databind.deser.std.JdkDeserializers not found, so I degrade the version to "2.9.10.5" @SteNicholas @fengjiachun

**Comment by SteNicholas** [comment]
@zongtanghu I thought that you should keep the previous change and solve the problem that the class com.fasterxml.jackson.databind.deser.std.JdkDeserializers not found. After the 2.10 version of jackson-databind may have the CVE, how do you solve the same problem?

**Comment by zongtanghu** [comment]
@SteNicholas  Okay, I will do some deep research into this issue.

**Comment by zongtanghu** [comment]
I upgraded the version of jackson.databind and jackson.dataformat to 2.10.4 and verified the test case in my local enviroment, it all passed.It can resolove the issue which "com.fasterxml.jackson.databind.deser.std.JdkDeserializers" class not found above.

**Pull request merged**
