### PR TITLE
upgrade grpc to 1.50.2

### LINKED ISSUE #734: sofa-jraft依赖的grpc1.17.0版本老旧而且缺陷多，建议升级依赖版本
### Describe the bug
grpc 1.17.0 以及其依赖的很多组件版本都有很多缺陷，其中比较严重的是grpc-java 1.28之前的版本所依赖的netty存在的Received DATA frame for an unknown stream缺陷。
sofa-jraft 1.3.9和修复缺陷后的grpc并不兼容，运行过程中要么提示类找不到，要么提示属性不存在，建议做一下新版本兼容性升级。

### PR DESCRIPTION
**Pull request by KomachiSion**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #734 and #841 .

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by fengjiachun** [comment]
check_format 失败，可以本地先执行一下 mvn compile（会自动 format） 再提交代码

**Comment by fengjiachun** [comment]
也需要签一下 CLA， 感谢

**Comment by KomachiSion** [comment]
image
reformat code finished, CLA signed but check can't pass.

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
Good job:+1

**Comment by KomachiSion** [comment]
@fengjiachun Is there plan to release recently?

**Comment by fengjiachun** [comment]
> @fengjiachun Is there plan to release recently?

ASAP

**Pull request merged**
