### PR TITLE
feat/priority_by_zongtanghu

### PR DESCRIPTION
**Pull request by fengjiachun**
#334

### CODE REVIEW

**Comment by killme2008** [comment]
Can we merge this PR ? @fengjiachun @zongtanghu

**Comment by fengjiachun** [comment]
I will do the jepsen test ASAP @killme2008

**Comment by zongtanghu** [comment]
> I will do the jepsen test ASAP @killme2008

Nice!

**Comment by fengjiachun** [comment]
[SOFAJRaft jepsen](https://github.com/sofastack/sofa-jraft-jepsen)


### `bash run_test.sh --testfn configuration-test`
(configuration-test: remove and add a random node.)
```
INFO [2019-11-25 18:58:52,064] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 0},
    :last-op
    {:process 2,
     :type :ok,
     :f :read,
     :value 0,
     :index 5235,
     :time 147978813819},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ
```

### ` bash run_test.sh --testfn bridge-test`
(bridge-test: weaving the network into happy little intersecting majority rings)

```
INFO [2019-11-25 19:03:46,562] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 2},
    :last-op
    {:process 0,
     :type :ok,
     :f :read,
     :value 2,
     :index 5209,
     :time 149184886347},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

```

### `bash run_test.sh --testfn pause-test`
(pause-test: pausing random node with SIGSTOP/SIGCONT.)

```
INFO [2019-11-25 19:09:16,352] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 1,
      :type :invoke,
      :f :write,
      :value 4,
      :index 3770,
      :time 115181152072}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 1,
      :type :invoke,
      :f :write,
      :value 4,
      :index 3770,
      :time 115181152072}
     {:process 2,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3767,
      :time 115109160026}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 3,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3772,
      :time 115238640807}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 3,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3772,
      :time 115238640807}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 1,
      :type :invoke,
      :f :write,
      :value 4,
      :index 3770,
      :time 115181152072}
     {:process 2,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3767,
      :time 115109160026}
     {:process 3,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3772,
      :time 115238640807}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 2,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3767,
      :time 115109160026}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 2,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3767,
      :time 115109160026}
     {:process 3,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3772,
      :time 115238640807}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}
     {:process 1,
      :type :invoke,
      :f :write,
      :value 4,
      :index 3770,
      :time 115181152072}
     {:process 3,
      :type :invoke,
      :f :write,
      :value 2,
      :index 3772,
      :time 115238640807}]}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending []}
   {:model {:value 1},
    :last-op
    {:process 5,
     :type :ok,
     :f :read,
     :value 1,
     :index 3831,
     :time 145594756788},
    :pending
    [{:process 0,
      :type :invoke,
      :f :cas,
      :value [4 3],
      :index 3768,
      :time 115162466175}]}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

```

### `bash run_test.sh --testfn crash-test`
(crash-test: killing random nodes and restarting them.)

```
INFO [2019-11-25 19:16:14,998] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true, :model {:value 4}, :final-paths (), :configs ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

```

### `bash run_test.sh --testfn partition-test`
(partition-test: Cuts the network into randomly chosen halves.)

```
INFO [2019-11-25 19:18:32,708] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :indep
 {:valid? true,
  :results
  {0
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 2,
        :type :ok,
        :f :write,
        :value 1,
        :index 197,
        :time 3433914385},
       :pending []}),
     :final-paths ()},
    :valid? true},
   7
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 2,
        :type :ok,
        :f :write,
        :value 1,
        :index 1607,
        :time 22150718474},
       :pending []}),
     :final-paths ()},
    :valid? true},
   20
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 40,
        :type :ok,
        :f :write,
        :value 4,
        :index 4214,
        :time 57845894907},
       :pending []}),
     :final-paths ()},
    :valid? true},
   1
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 2,
        :type :ok,
        :f :read,
        :value 0,
        :index 398,
        :time 5890337661},
       :pending []}),
     :final-paths ()},
    :valid? true},
   4
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 4,
        :type :ok,
        :f :read,
        :value 3,
        :index 1007,
        :time 15271314895},
       :pending []}),
     :final-paths ()},
    :valid? true},
   15
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 0}, :final-paths (), :configs ()},
    :valid? true},
   21
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 40,
        :type :ok,
        :f :read,
        :value 2,
        :index 4431,
        :time 60377327269},
       :pending []}),
     :final-paths ()},
    :valid? true},
   13
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 0,
        :type :ok,
        :f :write,
        :value 2,
        :index 2808,
        :time 37243267599},
       :pending []}),
     :final-paths ()},
    :valid? true},
   22
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 40,
        :type :ok,
        :f :cas,
        :value [3 0],
        :index 4443,
        :time 60554131908},
       :pending []}),
     :final-paths ()},
    :valid? true},
   6
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 2},
       :last-op
       {:process 2,
        :type :ok,
        :f :cas,
        :value [0 2],
        :index 1407,
        :time 19862115144},
       :pending []}),
     :final-paths ()},
    :valid? true},
   17
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 29,
        :type :ok,
        :f :write,
        :value 0,
        :index 3621,
        :time 50546896658},
       :pending []}
      {:model {:value 3},
       :last-op
       {:process 33,
        :type :ok,
        :f :write,
        :value 3,
        :index 3620,
        :time 50536115274},
       :pending []}),
     :final-paths ()},
    :valid? true},
   3
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 0,
        :type :ok,
        :f :write,
        :value 1,
        :index 806,
        :time 13127406995},
       :pending []}),
     :final-paths ()},
    :valid? true},
   12
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 1},
       :last-op
       {:process 1,
        :type :ok,
        :f :write,
        :value 1,
        :index 2611,
        :time 34765271552},
       :pending []}),
     :final-paths ()},
    :valid? true},
   2
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 4,
        :type :ok,
        :f :read,
        :value 4,
        :index 609,
        :time 9538791404},
       :pending []}),
     :final-paths ()},
    :valid? true},
   19
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 46,
        :type :ok,
        :f :read,
        :value 0,
        :index 4027,
        :time 55556518013},
       :pending []}),
     :final-paths ()},
    :valid? true},
   11
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 1,
        :type :ok,
        :f :cas,
        :value [2 0],
        :index 2416,
        :time 32011004496},
       :pending []}),
     :final-paths ()},
    :valid? true},
   9
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 1,
        :type :ok,
        :f :read,
        :value 3,
        :index 2009,
        :time 27112391481},
       :pending []}),
     :final-paths ()},
    :valid? true},
   5
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 3,
        :type :ok,
        :f :write,
        :value 0,
        :index 1208,
        :time 17548039388},
       :pending []}
      {:model {:value 4},
       :last-op
       {:process 2,
        :type :ok,
        :f :write,
        :value 4,
        :index 1206,
        :time 17547998215},
       :pending []}
      {:model {:value 3},
       :last-op
       {:process 1,
        :type :ok,
        :f :write,
        :value 3,
        :index 1209,
        :time 17549682791},
       :pending []}),
     :final-paths ()},
    :valid? true},
   14
   {:timeline {:valid? true},
    :linear
    {:valid? true, :model {:value 2}, :final-paths (), :configs ()},
    :valid? true},
   16
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 0},
       :last-op
       {:process 33,
        :type :ok,
        :f :write,
        :value 0,
        :index 3422,
        :time 48240567026},
       :pending []}),
     :final-paths ()},
    :valid? true},
   10
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 3},
       :last-op
       {:process 4,
        :type :ok,
        :f :write,
        :value 3,
        :index 2205,
        :time 29356295164},
       :pending []}),
     :final-paths ()},
    :valid? true},
   18
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 46,
        :type :ok,
        :f :write,
        :value 4,
        :index 3817,
        :time 53010130235},
       :pending []}),
     :final-paths ()},
    :valid? true},
   8
   {:timeline {:valid? true},
    :linear
    {:valid? true,
     :configs
     ({:model {:value 4},
       :last-op
       {:process 2,
        :type :ok,
        :f :read,
        :value 4,
        :index 1807,
        :time 24720035835},
       :pending []}),
     :final-paths ()},
    :valid? true}},
  :failures []},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

```

### `bash run_test.sh --testfn partition-majority-test`
(partition-majority-test: Cuts the network into randomly majority groups.)
```
INFO [2019-11-25 19:22:22,283] main - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :linear
 {:valid? true,
  :configs
  ({:model {:value 1},
    :last-op
    {:process 2,
     :type :ok,
     :f :read,
     :value 1,
     :index 4931,
     :time 148170257500},
    :pending []}),
  :final-paths ()},
 :timeline {:valid? true},
 :valid? true}


Everything looks good! ヽ(‘ー`)ノ

```

**Pull request merged**
